### ISSUE TITLE
Psr16CacheStorage is saving without TTL

### ISSUE THREAD

**Issue by sergiuPHP** [Kevinrob/guzzle-cache-middleware#102]
In "Psr16CacheStorage" don't use ttl from CacheEntry how does for example DoctrineCacheStorage

Please update implementations of save function to something like:

$this->cache->set($key, $data, $date->getTTL());

**Comment by francescolaffi** [comment]
@sergiuPHP could you do a PR to fix this? even if you never contributed is a good first contribution, otherwise let me know as I'll take it up

btw I'm not a mantainer of this project, just interested in seeing this fixed

**Comment by sergiuPHP** [comment]
Hi, Sure. Happy to help.

**Comment by Kevinrob** [comment]
https://github.com/Kevinrob/guzzle-cache-middleware/releases/tag/v3.2.1
