### ISSUE TITLE
Calls with different request headers use same cache file

### ISSUE THREAD

**Issue by jamieburchell** [Kevinrob/guzzle-cache-middleware#105]
I'm not sure if this is by design, a bug, or something that needs to be coded around. I have two requests to the same URL, one has a custom HTTP header and the other doesn't. Whichever URL is called first results in a cache miss and cache file created, then the next call is a cache hit. Does this library not take in to account the request headers? How is the cache hit determined?

I'm using v2.0.2, guzzlehttp 6.2.

**Comment by jamieburchell** [comment]
I think I need to look at implementing the Vary header in responses.

**Comment by Kevinrob** [comment]
Yes, `vary` is the way to do that. 👍
