### ISSUE TITLE
Is Must-Revalidate supported?

### ISSUE THREAD

**Issue by jenkoian** [Kevinrob/guzzle-cache-middleware#110]
I receive a response with the following headers:

`Cache-Control: public, max-age=3600, must-revalidate`
`Vary: Accept-Language`
`Last-Modified: Mon, 22 Jun 1998 15:03:52 GMT`

What I would expect in this case is for a revalidation request to be made and the headers updated in the cache if a 304 or the cache entry removed/invalidated if a 200. 

What I'm seeing though is that the `must-revalidate` is ignored and the response is cached for the time stipulated in `max-age`. 

It feels like we need something in [here](https://github.com/Kevinrob/guzzle-cache-middleware/blob/master/src/Strategy/PrivateCacheStrategy.php#L64) that handles the `must-revalidate` case?

Sorry I can't give any more information than this, feel free to bounce questions back to me though or of course enlighten me if I've misunderstood. 

Thanks!

**Comment by Kevinrob** [comment]
This library don't handle `must-revalidate` yet.  
But `must-revalidate` doesn't work like you said. It's only for when the cache entry become stale. `must-revalidate` said that you can't serve stale content.

You can read the definition of [RFC 7234](https://tools.ietf.org/html/rfc7234#section-5.2.2.1)

**Comment by jenkoian** [comment]
ah yes you're right! I was previously using https://github.com/guzzle/cache-subscriber/blob/master/src/ValidationSubscriber.php which seems to send a validation request if the must-revalidate header is present. 

Thanks for the info, I'll close this now.
