### ISSUE TITLE
Permanent cache

### ISSUE THREAD

**Issue by kubk** [Kevinrob/guzzle-cache-middleware#111]
Permanent cache is useful while testing Guzzle clients. Guzzle already provides [MockHandler](http://docs.guzzlephp.org/en/stable/testing.html) for testing API clients but for big clients it is tedious to generate manually all of the response fixtures.
A middleware for permanent cache will solve this issue. Basically permanent cache is `GreedyCacheStrategy` without the `ttl` option.
Can make a PR.

For example, [Geocoder PHP library](https://github.com/geocoder-php/provider-integration-tests) uses similar approach with cached responses:
https://github.com/geocoder-php/provider-integration-tests/blob/master/src/CachedResponseClient.php#L78

**Comment by Kevinrob** [comment]
Okay, let's make a PR 👍  
Something like `PermanentCacheStrategy`?

**Comment by kubk** [comment]
@Kevinrob Thanks for the response.
Guess I'll just use very big TTL, for example 30 years.

BTW Very well written library :heart:
