### ISSUE TITLE
Flysystem returns "File not Found" error on DELETE, POST, PUT calls

### ISSUE THREAD

**Issue by marcus-at-localhost** [Kevinrob/guzzle-cache-middleware#127]
#### Versions used
```
"guzzlehttp/guzzle": "^6.3",
"kevinrob/guzzle-cache-middleware": "^3.3",
"league/flysystem": "^1.0",
```
Tested locally on Win with PHP 5.6 and online Linux PHP 7.3 -same result.

#### Description

I noticed a strange behavior with this setup:

```php
$cache = new CacheMiddleware(
	new \Kevinrob\GuzzleCache\Strategy\PrivateCacheStrategy (
		new FlysystemStorage(
			new Local($cachePath . '/guzzle')
		),
		$ttl
	)
);
$this->stack->push($cache, 'cache');
```
GET requests are working fine, but for some reasons with POST, DELETE, PUT requests, the Server returns the following:

![image](https://user-images.githubusercontent.com/1337223/79115546-6e6dca00-7d86-11ea-860c-543abc97a13c.png)

Flysystem tries to delete cache files that aren't existing.

If I go into FlysystemStorage.php https://github.com/Kevinrob/guzzle-cache-middleware/blob/5cd04b49699e6e8ba7549686529c4c64819601ce/src/Storage/FlysystemStorage.php#L19 and add `['disable_asserts' => true]` as recommended here: (https://flysystem.thephpleague.com/v1/docs/advanced/performance/)

```php
    public function __construct(AdapterInterface $adapter)
    {
        $this->filesystem = new Filesystem($adapter, ['disable_asserts' => true]);
    }
```
it seems to work fine. Unfortunately I can't add that here `new Local($cachePath . '/guzzle')`.

When I explicitly set 

```php
$cache->setHttpMethods(['GET' => true, 'POST' => false, 'DELETE' => false, 'PUT' => false]);
$this->stack->push($cache, 'cache');
```

I also got rid of the error, but now cache files are showing up in my directory, which I would not expect (since caching is turned off).

I'm not sure if I missed something. I used the PSR6 caching before and that worked fine, if I remember right.

Doesn't matter if I use Private or Greedy cache strategy.

Somebody has an idea?

**Comment by Kevinrob** [comment]
Thank you for this report.
When you do a POST, DELETE or PUT requests, we need to invalidate the corresponding route for GET requests (RFC).

Maybe we need to adapt `FlysystemStorage` for checking if the file exists before trying to delete it. (or we can catch the error).

Can you make a PR for this changes?
