### ISSUE TITLE
[Question] Specifying TTL For Laravel Cache

### ISSUE THREAD

**Issue by benbelmour** [Kevinrob/guzzle-cache-middleware#141]
I have followed this example in terms of implementing caching within my application:

![image](https://user-images.githubusercontent.com/79989595/118126060-af079f00-b3ef-11eb-8a97-9ab1122bc69d.png)

In terms of this example, how would one set the TTL?

**Comment by markspare** [comment]
You don't specify the TTL, it is specified in the response from the server.

If the server is not returning cache headers you can specify a greedy cache strategy and specify your own TTL but this it shouldn't be used unless absolutely necessary.

**Comment by benbelmour** [comment]
> You don't specify the TTL, it is specified in the response from the server.
> 
> If the server is not returning cache headers you can specify a greedy cache strategy and specify your own TTL but this it shouldn't be used unless absolutely necessary.
> 
> https://github.com/Kevinrob/guzzle-cache-middleware/blob/master/src/Strategy/GreedyCacheStrategy.php

What header does it look at for the TTL?

**Comment by markspare** [comment]
`Cache-Control` and `Expires`: https://github.com/Kevinrob/guzzle-cache-middleware/blob/57c579392ef24d6afe72a00ccd73f09ae35a9d24/src/Strategy/PrivateCacheStrategy.php#L71
