### ISSUE TITLE
Cache with a TTL

### ISSUE THREAD

**Issue by Kevinrob** [Kevinrob/guzzle-cache-middleware#15]
like @EAnushan start in #14

**Comment by EAnushan** [comment]
You may need to change:
```
$lifeTime >= 0
```
to
```
$lifeTime > 0
```
Doctrine caching will cache an item forever if you set the TTL to 0. This means it will never leave the cache. We shouldn't cache HTTP responses that have a TTL of 0.

**Comment by Kevinrob** [comment]
Yes, we must cache forever when we have the header `Etag` or `Last-Modified`. Or at least the maximum possible.
With that, a server can serve a content without freshness (directly stale) but with a hash (`Etag`) or a date (`Last-Modified`). The cache must keep this entry and ask for a validation before using it. If the server respond with a 304 (no content with it), the cache can use this entry.
There isn't any expiration delay for using it.

This is particularly useful for heavy or slow responses to calculate.

**Comment by EAnushan** [comment]
Ah I see. This makes sense.
