### ISSUE TITLE
Missing dependency on guzzlehttp/promises and not compatible with v2.0

### ISSUE THREAD

**Issue by lazka** [Kevinrob/guzzle-cache-middleware#175]
After the recent update of `guzzlehttp/promises` to v2 (https://github.com/guzzle/promises) with breaking changes this package is broken by it:

> PHP Fatal error:  Uncaught Error: Call to undefined function GuzzleHttp\Promise\inspect_all() in /vendor/kevinrob/guzzle-cache-middleware/src/CacheMiddleware.php:113

I'd guess a fix would be to explicitly depend on `guzzlehttp/promises`, either v1 or v2, or both somehow.

**Comment by juanparati** [comment]
I also faced the same issue, and I fixed the issue forcing to use promises 1.0 as dependency.

**Comment by dbclkh** [comment]
How about using the replacement function instead?

Utils::inspectAll

https://packagist.org/packages/guzzlehttp/promises

**Comment by Kevinrob** [comment]
https://github.com/Kevinrob/guzzle-cache-middleware/pull/178 fixes this, no?
