### ISSUE TITLE
Error and TTL

### ISSUE THREAD

**Issue by Zyles** [Kevinrob/guzzle-cache-middleware#19]
I get "PHP Fatal error:  Class 'CacheMiddleware' not found" trying to use your example filecache (which also is missing a ")" at the end) and how do you specify the TTL on the cache?

**Comment by Kevinrob** [comment]
Do you use Composer? Do you include the bootstrap file? https://getcomposer.org/doc/01-basic-usage.md
If you don't use Composer, you have to manually include/require the files in your script.

You don't set a TTL, this library will use HTTP cache headers (`Cache-Control` or `Expire`) for calculating the TTL for the response. The goal is to respect the RFC 7234.

**Comment by Zyles** [comment]
I do, everything else is working through Composer... will have to investigate more later.

So the rest API I am querying sets a header and the library will automatically save and delete it for that amount of time?

**Comment by Kevinrob** [comment]
Ok, and did you add `use Kevinrob\GuzzleCache;`at the begining?

Yes, it's the server that indicate if and how the response can be cached. If the isn't any indication, we are not allowed to cache it.
You can found information about that like [this article](http://www.mobify.com/blog/beginners-guide-to-http-cache-headers/).

Of course, you can implement your own `CacheProvider` like that:
```php
use Doctrine\Common\Cache\Cache;
use Psr\Http\Message\ResponseInterface;

class FixTTLCache extends PrivateCache
{

    /**
     * @var int
     */
    protected $ttl;

    
    public function __construct(Cache $cache = null, $ttl = 30)
    {
        parent::__construct($cache);

        $this->ttl = $ttl;
    }

    protected function getCacheObject(ResponseInterface $response)
    {
        return new CacheEntry($response, new \DateTime('+' . $this->ttl . ' seconds'));
    }

}
```
And use it like that:
```php
$stack->push(new CacheMiddleware(
  new FixTTLCache(
    new FilesystemCache('/tmp/'),
    60 
  )
));
```

PS: I don't test those codes, I just write it!

**Comment by Kevinrob** [comment]
After having reading about that, a cache is allowed to set a little TTL if they isn't any indication from the server (no `Expire`, no `Cache-Control`). Maybe I will add that :+1:

**Comment by kslr** [comment]
Hello, can you ignore the Cache-Control cache?

**Comment by Kevinrob** [comment]
@kslr please create a new issue if you have a problem. But `GreedyCacheStrategy` is what you looking for ;)
