### ISSUE TITLE
Implement "Request Cache-Control Directives"

### ISSUE THREAD

**Issue by Kevinrob** [Kevinrob/guzzle-cache-middleware#25]
https://tools.ietf.org/html/rfc7234#section-5.2.1

With `Pragma` fallback => https://tools.ietf.org/html/rfc7234#section-5.4

**Comment by Kevinrob** [comment]
- [ ] `Cache-Control: no-store` => don't cache response
- [ ] `Cache-Control: no-cache` => don't return cached response (but cache it)
- [ ] `Cache-Control: max-age=XX` => don't return cached response that have a `Age` > XX
- [ ] `Cache-Control: max-stale` => client ask for a stale response if exist
- [ ] `Cache-Control: max-stale=XX` => client ask for a stale reponse of max XX seconds after stale time
- [ ] `Cache-Control: min-fresh=XX` => the cache response must still be fresh in XX seconds
- [X] `Cache-Control: no-transform` => no touch at the response body (nothing to do for us)
- [ ] `Cache-Control: only-if-cached` => client ask for a cached response, `504` if not exist in cache
- [ ] `Pragma: no-cache` => same as `Cache-Control: no-cache` but only take care if no `Cache-Control` at all

**Comment by Thinkscape** [comment]
:+1:  
Inspiration: https://github.com/Guzzle3/plugin-cache/blob/master/DefaultRevalidation.php
