### ISSUE TITLE
Remove dependency on Doctrine/Cache

### ISSUE THREAD

**Issue by Kevinrob** [Kevinrob/guzzle-cache-middleware#27]
With a custom interface for caching with a implementing of it that take a `Doctrine/Cache` in the constructor for compatibility.

**Comment by Kevinrob** [comment]
remove #26 after that.

**Comment by Thinkscape** [comment]
Actually I'd rename and refactor https://github.com/Kevinrob/guzzle-cache-middleware/blob/master/src/PrivateCache.php.

It seems like that's a good candidate to become `class DoctrineCacheBackend`.

There is however a noticeable amount of non-backend related stuff in there, like checking headers etc. Have you considered moving that into the middleware?

**Comment by Kevinrob** [comment]
I prefer to keep the caching logic out of the middleware. Like that we can have a private and a public (shared) cache.
I think that the middleware must keep the general logic of "checking" (save/fetch) without the logic of "determin-if-caching" (checking headers, etc...).

Like that, we can "plug" a different strategy of caching into the middleware. ([example](https://github.com/Kevinrob/guzzle-cache-middleware/issues/19#issuecomment-124967243))

**Comment by Kevinrob** [comment]
cf. #28

**Comment by Kevinrob** [comment]
This is OK with the PR #28
