### ISSUE TITLE
DoctrineCache produces essentially empty file

### ISSUE THREAD

**Issue by jamieburchell** [Kevinrob/guzzle-cache-middleware#31]
Using version ~0.6 and the example in the README to use the DoctrineCacheWrapper component.

No matter what I do, I just get the following folder structure and file:

`30\a7\1e\5d\66\05\8b\51\2e\b1\11\50\ad\5c\c2\6c\5a\5a\d4\80\fa\a1\c3\08\9a\e2\72\c9\ac\7d\7f\84\DoctrineNamespaceCacheKey[].doctrinecache.data`

The file always contains:

```
0
i:1;
```

This is when I am GETing resources behind a basic auth web service, which from what I can see is setting the correct cache headers.

```
< HTTP/1.1 200 OK
< Cache-Control: public
< Content-Type: application/json; charset=utf-8
< Expires: Sat, 05 Sep 2015 15:07:35 GMT
```

I'm assuming something's not right, but I have no idea what.

PHP 5.5.24 / Apache/2.2.15 (Unix)

Jamie

**Comment by Kevinrob** [comment]
I see the problem.
Currently, the `PrivateCacheStrategy` search a `Cache-Control` and if not found, an `Expires`. So in your headers, the `Expires: Sat, 05 Sep 2015 15:07:35 GMT` is never used.

The logic is not correct after re-reading the RFC, the `Expire` must be used even if a `Cache-Control` is present. I will try to fix it!

**Comment by Kevinrob** [comment]
Related to #11

**Comment by Kevinrob** [comment]
@jamieburchell Thanks for reporting this issue. Can you please re-try with `v0.6.1`?

**Comment by jamieburchell** [comment]
No problem. I thought perhaps I had done something wrong. Thanks for looking in to it, the earliest I can test the fix is Tuesday. I'll report back.

**Comment by jamieburchell** [comment]
I'm happy to report that this seems to have fixed the issue. More folders are being created now with files containing data and GuzzleHttp is not connecting to the service to fetch resources within the cache lifetime. Thanks for your help.
