### ISSUE TITLE
Does not work without Doctrine

### ISSUE THREAD

**Issue by shadowhand** [Kevinrob/guzzle-cache-middleware#32]
The simple example provided in the README:

```php
$stack->push(new CacheMiddleware(), 'cache');
```

does not work without Doctrine installed:

> Fatal error: Class undefined: Doctrine\\Common\\Cache\\ArrayCache in vendor/kevinrob/guzzle-cache-middleware/src/Strategy/PrivateCacheStrategy.php on line 61

Suggesting `doctrine/cache` seems misleading if the package doesn't work without it.

**Comment by Kevinrob** [comment]
You're right. This is not optimal.

By default (without parameter) the constructor of `CacheMiddleware` use a `PrivateCacheStrategy` with `new DoctrineCacheWrapper(new ArrayCache())`.

I will change that,

**Comment by shadowhand** [comment]
It would be nice if the Doctrine remained optional and the default created a temporary file for storage. Or if a [Flysystem](http://flysystem.thephpleague.com/) adapter was included.

**Comment by Kevinrob** [comment]
I didn't know Flysystem. I will take a look!

**Comment by Kevinrob** [comment]
@shadowhand: With the version `0.6.2` the simple example:
```php
$stack->push(new CacheMiddleware(), 'cache');
```
work without `doctrine/cache`.

Thanks for reporting this issue!
