### ISSUE TITLE
Use and test with etag params

### ISSUE THREAD

**Issue by samuelecarpene** [Kevinrob/guzzle-cache-middleware#37]
Hi i need to use this package with guzzle 6 and etag cache.
Then i need to test if the caching is working.

Can you help me becuause i don't know how to do it.

Thank you in advance.

**Comment by Kevinrob** [comment]
Hi,
of course! 

```php
use GuzzleHttp\Client;
use GuzzleHttp\HandlerStack;
use Kevinrob\GuzzleCache\CacheMiddleware;

// Create default HandlerStack
$stack = HandlerStack::create();

// Create the cache middleware
// You can customise the cache storage, see the doc
$cache = new CacheMiddleware();

// Add this middleware to the top with `push`
$stack->push($cache, 'cache');

// Initialize the client with the handler option
$client = new Client(['handler' => $stack]);

// Now you can use Guzzle...
```
To test if the cache HIT, you can check the header:
```php
$response->getHeaderLine(CacheMiddleware::HEADER_CACHE_INFO)
```

If you have any problem, tell me!

**Comment by Kevinrob** [comment]
If you need more help, re-open this issue.

**Comment by gnutix** [comment]
Hello! I just needed to do the exact same thing in my tests and your code worked perfectly (it returns "HIT" or "MISS").

However, when I try to do something like this : 
```
$this->assertEquals(304, $response->getStatusCode());
$this->assertEmpty($response->getBody()->getContents());
```

It fails and gives me the same data as the first request (200, with a body). Any idea why ?

**Comment by Kevinrob** [comment]
@gnutix The cache will change code from `304` to `200` and fill the `body` with the cache. It's transparent from the caller.
You can check `CacheMiddleware::HEADER_CACHE_INFO` header for debugging/testing information.

**Comment by gnutix** [comment]
OK thanks!
