### ISSUE TITLE
Response Body Rewind

### ISSUE THREAD

**Issue by EAnushan** [Kevinrob/guzzle-cache-middleware#40]
If the response body is consumed using `$response->getBody()->getContents()`, then if another cache hit occurs during the same request, the cache hit will have an already consumed body.

Looking at CacheEntry, https://github.com/Kevinrob/guzzle-cache-middleware/blob/ba5994e86e895a728e91e00ab923debac39fb391/src/CacheEntry.php#L232, __sleep seems to handle this when we serialize. But if using an in memory (array) storage, and the entry is used multiple times during the same request, the stream is never rewinded, and instead, served with the stream pointer wherever it was left at by the previous request.

**Comment by Kevinrob** [comment]
Thanks @EAnushan for this issue.
What do you think of the PR #41? Does it fix this issue?
