### ISSUE TITLE
[Question]: Force cache

### ISSUE THREAD

**Issue by debo** [Kevinrob/guzzle-cache-middleware#44]
Is there a way with the current implementation to force the client to cache the response regardless the headers coming from the response? I would like to ask the response coming from an API but it is so badly implemented that it doesn't send back proper headers. What would be the best way to go about it?

**Comment by jeromegamez** [comment]
You can use the GreedyCacheStrategy, introduced with #38.

**Comment by debo** [comment]
Hey @jeromegamez thanks for the head up, the documentation on here it's a bit meh unfortunately, I wasn't aware of that (read as I didn't even check the code to be honest :-P).

I'll have a look into it thanks.

**Comment by debo** [comment]
@jeromegamez you made my day, that was amazing. Where do we have to sign to have this middleware integrated in the core? :D

**Comment by jeromegamez** [comment]
It already is :D

**Comment by debo** [comment]
@jeromegamez I meant this entire plugin to become part of GuzzleHttp core :)

**Comment by Kevinrob** [comment]
The documentation need some work :smile: (cf. #42).

**Comment by Kevinrob** [comment]
@debo can we close this issue? Have you able to use the GreedyCacheStrategy?

**Comment by debo** [comment]
@Kevinrob oh yes sorry, I forgot to update the issue. Thanks a lot.
