### ISSUE TITLE
Improve Psr6CacheStorage

### ISSUE THREAD

**Issue by BenMorel** [Kevinrob/guzzle-cache-middleware#48]
I noticed a few points that I think could be improved in the PSR-6 storage implementation:

# Double serialization

The implementation uses [serialize()](https://github.com/Kevinrob/guzzle-cache-middleware/blob/master/src/Storage/Psr6CacheStorage.php#L47) and [unserialize()](https://github.com/Kevinrob/guzzle-cache-middleware/blob/master/src/Storage/Psr6CacheStorage.php#L31) explicitly. Is this necessary? `CacheItemInterface::set()` expects a [serializable value](https://github.com/php-fig/cache/blob/master/src/CacheItemInterface.php#L70-L71), not a serialized string. As a consequence, I think that the `CacheEntry` is serialized twice, which has an impact on both performance and storage space. As far as I can see, the calls to `serialize()` and `unserialize()` could simply be removed.

# Useless read from the cache

You use [CachePoolInterface::getItem()](https://github.com/Kevinrob/guzzle-cache-middleware/blob/master/src/Storage/Psr6CacheStorage.php#L46) to retrieve a `CacheItemInterface`, on which you can call `set()`. As far as I understand it, you're only doing this because you can't create a `CacheItemInterface`: it's an interface; so you're getting one from the `CacheItemPoolInterface` out of simplicity. But this has a performance impact: you're reading from the cache for nothing. A solution could be to create a very simple `CacheItemInterface` implementation that you would instantiate before `save()`ing it in the pool.

# Missing expiration time

`CacheItemInterface` features an [expiresAt()](https://github.com/php-fig/cache/blob/master/src/CacheItemInterface.php#L90) method; it would be nice to set an expiration date-time computed from `$data->getTTL()`, similar to the [Doctrine Cache implementation](https://github.com/Kevinrob/guzzle-cache-middleware/blob/master/src/Storage/DoctrineCacheStorage.php#L46).

If I'm mistaken somewhere, please let me know. Otherwise I'll be happy to submit a PR to fix the above points!

**Comment by webda2l** [comment]
Yes for theses 3 points, current PSR-6 implementation is perfectible.

**Comment by Kevinrob** [comment]
It's OK for me if you would like to make a PR for this :+1:

**Comment by BenMorel** [comment]
PR sent :+1:
