### ISSUE TITLE
In the dark...

### ISSUE THREAD

**Issue by TCB13** [Kevinrob/guzzle-cache-middleware#55]
I've a page doing some REST queries using Guzzle 6. It works fine, however sometimes it gets to slow because it's always making queries. I found out that guzzle-cache-middleware is supposed to cache responses from the remote API.

However I can't get it to work, my code follows something like:

```
use GuzzleHttp\Client;
use GuzzleHttp\HandlerStack;
use League\Flysystem\Adapter\Local;
use Kevinrob\GuzzleCache\CacheMiddleware;
use Kevinrob\GuzzleCache\Strategy\PrivateCacheStrategy;
use Kevinrob\GuzzleCache\Storage\FlysystemStorage;

(...)

$stack = HandlerStack::create();
$stack->push(
  new CacheMiddleware(
    new PrivateCacheStrategy(
      new FlysystemStorage(
        new Local("/tmp/sitex")
      )
    )
  ), 
  "cache"
);


// Request
$client = new Client([
    "handler"  => $stack,
    "base_uri"  => "http://...,
    "timeout"   => 2.0,
]);

$response = $client->request("GET", "/posts", [
(...)
```

After running the code I don't get any errors or warnings. Guzzle still gives me the API response, however nothing new appear into `/tmp/sitex`.

Do I need to set anything after the request to cache the response? Are there options like setting the TTL of the responses?

The documentation doesn't explain any of this, so if someone could help me it would be nice :) Thanks!

**Comment by jeromegamez** [comment]
This sounds strange... Have you looked at the response headers of the endpoint you're requesting? Perhaps they state that the response shouldn't be cached.

Just to make sure (without knowing the endpoint), could you try using the GreedyCacheStrategy and verify that still nothing is written tou your filesystem? You you find files, this probably means the response "doesn't want" to be cached.

**Comment by TCB13** [comment]
@jeromegamez my response doesn't say anything about caching.

Response headers from `curl` (for example):

```
curl -i http://.../v2/issues
HTTP/1.1 200 OK
Date: Sun, 22 May 2016 19:21:05 GMT
Server: Apache
X-Powered-By: PHP/7.0.6
X-Content-Type-Options: no sniff
Access-Control-Expose-Headers: X-WP-Total, X-WP-TotalPages
Access-Control-Allow-Headers: Authorization
X-WP-Total: 1
X-WP-TotalPages: 1
Allow: GET
Transfer-Encoding: chunked
Content-Type: application/json; charset=UTF-8
```

The code using the GreedyCacheStrategy:

```
$stack->push(
	  new CacheMiddleware(
		new GreedyCacheStrategy(
		  new FlysystemStorage(
			new Local("/tmp/sitex")
		  ),
		  180
		)
	  ), 
	  "cache"
	);
```

Still nothing of the FS. Thank you.

**Comment by TCB13** [comment]
@jeromegamez just right after my last comment I refreshed it some times and apparently it's caching now!

```
$headers = $response->getHeaders();
print $headers["X-Kevinrob-Cache"][0];
```

Says "HIT" now, but at the first tries it was always missing. Should I use `GreedyCacheStrategy`? What that really means on this context?

**Comment by jeromegamez** [comment]
The GreedyCacheStrategy always caches responses with a fixed TTL, even when the response explicitely isn't to be cached. This can be useful in certain cases but should not be used by default. There seems to be another issue - you should try going through the process e.g. with xdebug and find out where things go south... Still strange - perhaps someone else has a better idea :)

**Comment by TCB13** [comment]
@jeromegamez it is working with the GreedyCacheStrategy, so I'll leave at it right now and debug it later this week.

Thanks for the fast reply.
