### ISSUE TITLE
Laravel Cache::store('file')

### ISSUE THREAD

**Issue by J-Yen** [Kevinrob/guzzle-cache-middleware#56]
Does the following code work?

```
$stack->push(
	new CacheMiddleware(
		new PrivateCacheStrategy(
			new LaravelCacheStorage(
				Cache::store('file')
			)
		)
	),
    'cache'
);
```

Where is the cache saved? Normally in storage/framework/cache but i don't find the cache file.

**Comment by Kevinrob** [comment]
@M165437 Can you help us on this?

**Comment by M165437** [comment]
@J-Yen Have a look at the file `config/cache.php` and https://laravel.com/docs/5.2/cache. Make sure caching works outside of the Guzzle middleware before using it, e.g. in the router

```
Route::get('/', function () {
    Cache::store('file')->put('hello', 'world', 5);
    $value = Cache::store('file')->get('hello');
    return $value; // -> world
});
```

By the way, it's not one cache file but rather a folder structure. Correct, by default in `storage/framework/cache`.

**Comment by J-Yen** [comment]
Caching already works outside the Guzzle middleware and i already use it. But with the middleware, no new file or directory is created in the folder structure.

**Comment by M165437** [comment]
Can you post more of your code? The part you posted above should work.

**Comment by J-Yen** [comment]
```
class ConnectorService
{
    $connectionUrl = 'http://...';
    private $client;

    function __construct()
    {
        $stack = HandlerStack::create();

        $stack->push(
            new CacheMiddleware(
                new PrivateCacheStrategy(
                    new LaravelCacheStorage(
                        Cache::store('file')
                    )
                )
            ),
            'cache'
        );
        $this->client = new GuzzleHttp\Client(['handler' => $stack]);
	}



public function post_request($postArgs)
 {
        $response = $this->client->request('POST', $this->connectionUrl, [
            'form_params' => $postArgs,
        ])->getBody();
        return json_decode($response);
}
```

**Comment by M165437** [comment]
Looks good. What about the response headers? Are you sure the response wants to be cached? You can check the headers with Laravel's dd() (dump and die) method, although you'd need to remove the `->getBody()` from your client request:

```php
public function post_request($postArgs)
 {
        $response = $this->client->request('POST', $this->connectionUrl, [
            'form_params' => $postArgs,
        ]);
        dd($response->getHeaders()); // temporarily
        return json_decode($response->getBody());
}
```

**Comment by J-Yen** [comment]
Ow yes that is the cause.

```
["Cache-Control"]=>
  array(1) {
    [0]=>
    string(62) "no-store, no-cache, must-revalidate, post-check=0, pre-check=0"
  }
  ["Pragma"]=>
  array(1) {
    [0]=>
    string(8) "no-cache"
  }

```

Thank you very much!

**Comment by M165437** [comment]
What's the `Cache-Control` header value?

**Comment by M165437** [comment]
You're welcome! :-)

**Comment by J-Yen** [comment]
Now only figure out how to change it :-)

**Comment by M165437** [comment]
@Kevinrob Honestly, I had the same struggle initially. :-) The `Cache-Control` header might be worth a paragraph in the README file.

**Comment by Kevinrob** [comment]
You can use the `GreedyCacheStrategy`. It doesn't care about headers from the server.
Yeah, I think that it can be added to the README :smile: (#42)

**Comment by J-Yen** [comment]
So i have changed my code to:

```
$stack->push(
   new CacheMiddleware(
        new GreedyCacheStrategy(
            new LaravelCacheStorage(
                Cache::store('file')
            ),
            5000
        )
    ),
    'cache'
);
```
But still no caching...

**Comment by M165437** [comment]
Try this in `App/Http/routes.php`. This works for me.

```php
use GuzzleHttp\Client;
use GuzzleHttp\HandlerStack;
use Illuminate\Support\Facades\Cache;
use Kevinrob\GuzzleCache\CacheMiddleware;
use Kevinrob\GuzzleCache\Storage\LaravelCacheStorage;
use Kevinrob\GuzzleCache\Strategy\GreedyCacheStrategy;

Route::get('/guzzle-cache-test', function () {
    $stack = HandlerStack::create();

    $stack->push(new CacheMiddleware(
        new GreedyCacheStrategy(
            new LaravelCacheStorage(
                Cache::store('file')
            ), 5000
        )
    ), 'cache');

    $client = new Client(['handler' => $stack]);
    $responseBody = $client->get('http://github.com')->getBody();

    return $responseBody->getContents();
});
```

**Comment by M165437** [comment]
What about File Permissions? Have you checked your error logs? Maybe Laravel isn't able to write the cache to the file system?

**Comment by J-Yen** [comment]
No errors in the error logs. It should be able to write the cache to the file system because it's working with your example and in the rest of my code?

**Comment by J-Yen** [comment]
It is a Lumen project, can this be a problem?

**Comment by M165437** [comment]
That's quite a valuable info. Did you uncommented the `$app->withFacades()` method call in the bootstrap/app.php file?

**Comment by M165437** [comment]
Well, of course, otherwise the caching wouldn't work at all.

**Comment by M165437** [comment]
So, if my example works, it's obviously not a problem with the middleware.

**Comment by J-Yen** [comment]
yes i did uncommented the $app->withFacades() method.
Does your example work or are you going to test it?

**Comment by M165437** [comment]
It works in Laravel. Lumen and Laravel are not the same thing. Something that works in Lumen will probably work in Laravel but not necessarily vice versa. Next time please specify your framework up front. The Laravel interface was created for and tested with Laravel. I don't know if it works with Lumen.

**Comment by J-Yen** [comment]
Yes you're right I forgot an important detail. Nevertheless thank you very much for the quick help.

**Comment by M165437** [comment]
Out of curiosity I set up a Lumen project. The route example above works fine. So it _is_ Lumen compatible. :-)

**Comment by Kevinrob** [comment]
Can we close this _issue_?

**Comment by M165437** [comment]
Yes, I think so.

**Comment by tuanpht** [comment]
I use this to check if cache works. Hope it help someone :)
```php
use GuzzleHttp\Client;
use GuzzleHttp\HandlerStack;
use Illuminate\Support\Facades\Cache;
use Kevinrob\GuzzleCache\CacheMiddleware;
use Kevinrob\GuzzleCache\Storage\LaravelCacheStorage;
use Kevinrob\GuzzleCache\Strategy\GreedyCacheStrategy;

Route::get('/guzzle-cache-test', function () {
    $stack = HandlerStack::create();

    $stack->push(new CacheMiddleware(
        new GreedyCacheStrategy(
            new LaravelCacheStorage(
                Cache::store('file')
            ), 5
        )
    ), 'cache');

    $client = new Client(['handler' => $stack]);
    $responseBody = $client->get('http://localhost:1234/time.php')->getBody();

    return $responseBody->getContents();
});
```

```php
// http://localhost:1234/time.php
echo 'SERVER TIME: ' . date('Y-m-d H:i:s') . PHP_EOL;
```

If cache works, time will be increased by 5 seconds.

**Comment by randhipp** [comment]
> 
> 
> Try this minimal example in `App/Http/routes.php`. This works for me.
> 
> ```
> use GuzzleHttp\Client;
> use GuzzleHttp\HandlerStack;
> use Illuminate\Support\Facades\Cache;
> use Kevinrob\GuzzleCache\CacheMiddleware;
> use Kevinrob\GuzzleCache\Storage\LaravelCacheStorage;
> use Kevinrob\GuzzleCache\Strategy\GreedyCacheStrategy;
> 
> Route::get('/guzzle-cache-test', function () {
>     $stack = HandlerStack::create();
> 
>     $stack->push(new CacheMiddleware(
>         new GreedyCacheStrategy(
>             new LaravelCacheStorage(
>                 Cache::store('file')
>             ), 5000
>         )
>     ), 'cache');
> 
>     $client = new Client(['handler' => $stack]);
>     $responseBody = $client->get('http://github.com')->getBody();
> 
>     return $responseBody->getContents();
> });
> ```

This method working for me
