### ISSUE TITLE
Rookie Question

### ISSUE THREAD

**Issue by JustinTBrown** [Kevinrob/guzzle-cache-middleware#58]
Does GCM store cache on the user's local machine by default? And then the storage interface build-ins are for server-side/remote caching?

**Comment by funivan** [comment]
you can store any data on user's local machine  using FlysystemStorage and LocalAdapter 
See: http://flysystem.thephpleague.com/adapter/local/

**Comment by JustinTBrown** [comment]
Hi thanks @funivan, that wasn't quite what I was asking. I was wondering what the default storage behaviour was for the "simple" implementation of GCM (guzzle-cache-middleware). Either way I'm attempting to use Doctrine for filesystem storage on the server itself.

**Comment by jeromegamez** [comment]
AFAIK, the default cache is in memory, that means: if you execute the same HTTP request multiple times during one script execution, only the first one goes actually out, the following requests come from memory.
