### ISSUE TITLE
Cache key

### ISSUE THREAD

**Issue by waynegibson** [Kevinrob/guzzle-cache-middleware#59]
How do you set a key and retrieve it?  When doing a GET request the cache is created successfully with laravel as Cache|:store('file').

In the LaravelCacheStorage public fetch method, I added this code snippet:
 \Log::info('Fetch key @ '. \Carbon\Carbon::now() .' with key: ' . $key);

In the try block of the public fetch method I added this snippet:
\Log::info('Fetch cache @ '. \Carbon\Carbon::now() .' with cache: ' . $cache);

In the LaravelCacheStorage public save method, I added this code snippet:
\Log::info('Save key @ '. \Carbon\Carbon::now() .' with key: ' . $key);

In the try block of the public save method I added this snippet:
 \Log::info('Lifetime @ '. \Carbon\Carbon::now() .' with lifetime: ' . $lifeTime);

In the logs, when making a GET request for the first time the fetch method is fired with not results, but a key is logged, then the save method was fired, which then created the cache file successfully, but what is the readable cache key name?

When doing the same GET request the fetch method is fired first again in the logs, and then logs save method which is also fired again.

If I copy the key from the log file, eg; 'eb88a9055662c8786d3400969ee4e407eb56c9cc3a780b9358f7c6bf1e2829e2' and use the LaravelCacheStorage public fetch method to retrieve the key, it fetches the key as expected.

But I can't check to see if a cache key exists, before firing off another GET request, as I don't know what the key name is? Where is key's name set? How does this work, as it does not seem to be using the cache file on consecutive GET requests.

**Comment by Kevinrob** [comment]
Did you found response to your answers? I close this issue for cleaning the project. Don't hesitate to response for help!
