### ISSUE TITLE
Cache invalidation/removal

### ISSUE THREAD

**Issue by mrtomstone** [Kevinrob/guzzle-cache-middleware#60]
Is there a simple way that I can invoke an invalidation or removal of the cache for a specific call (e.g. http://api.test.com/users/1).

I need to do this after a PUT request to the api to access the new data on the next GET request.

**Comment by Kevinrob** [comment]
The PR #39 try to do that, but it's in WIP state.  
You can do that by adding a middleware in your guzzle stack that will delete entry in the storage maybe.

**Comment by mrtomstone** [comment]
Oh yes, thats exactly what I am after. As it is WIP, I am reluctant to use it in a production system. Instead, is there a way that I can choose to never cache certain requests?
