### ISSUE TITLE
GreedyCacheStrategy does not work as expected

### ISSUE THREAD

**Issue by zobzn** [Kevinrob/guzzle-cache-middleware#62]
GreedyCacheStrategy depends on the response headers Etag and Last-Modified, though it should not.
If Response has any of this headers, then CacheEntry::hasValidationInformation returns true, then CacheEntry::getTTL returns 0, then CacheEntry saved without expiration instead of defined ttl.

**Comment by afoeder** [comment]
@zobzn : Any chance for you to provide a Pull-Request? Would be awesome if you could since you're already on the topic. If you need some help to get started just ask (me).

**Comment by Kevinrob** [comment]
@zobzn @afoeder The PR #86 should fix that! Can you check and tell me if it's ok for you?

**Comment by zobzn** [comment]
@Kevinrob thanks a lot!
Unfortunally I'm already switched from Guzzle to HTTPlug with GreedyCachePlugin, so i can't check your changes in real code.
But changes in PR https://github.com/Kevinrob/guzzle-cache-middleware/pull/86 looks ok.
