### ISSUE TITLE
Invalidating cache for certain route or url

### ISSUE THREAD

**Issue by StephanBis** [Kevinrob/guzzle-cache-middleware#71]
Hey, 

Is it possible to invalidate the whole cache with this middleware? Is it even possible to invalidate only the cache that belongs to a certain route or url? 
The docs seem to not explain this.

Kind regards,
Stephan

**Comment by Kevinrob** [comment]
Hey,

Not really, but you control the storage. So you can delete cache by empty the storage that you use.
Maybe a new feature to add!

By the way if you use standard strategy (private/public) you don't need to clear the cache if the server return good headers.
