### ISSUE TITLE
Caching POST requests

### ISSUE THREAD

**Issue by popkin** [Kevinrob/guzzle-cache-middleware#72]
is it posible to cache POST requests?

thanks in advance

**Comment by Kevinrob** [comment]
First thing, it's not a good idea to cache POST requests. POST requests exists for "posting" something, they have to reach the server.

But some server don't implement POST correctly... By default only GET is allowed to be cached (by the RFC too).
You can add others methods with `setHttpMethods(array $methods)` on `CacheMiddleware` like that:

```php
$cache = new CacheMiddleware();
$cache->setHttpMethods(['GET' => true, 'POST' => true]);
```

**Comment by popkin** [comment]
yeah, this server uses POST even for getting data :( it's a nightmare.

I'll try that, thanks

**Comment by tomswinkels** [comment]
Maybe add this to the readme? When you use Graphql it is always a post request!
