### ISSUE TITLE
How can i clear cache? GreedyCacheStrategy

### ISSUE THREAD

**Issue by tanys123** [Kevinrob/guzzle-cache-middleware#90]

**Comment by Kevinrob** [comment]
That's depend of the "Storage" that you use.

- If you use some files, just delete it
- If you use redis, clear it
- etc...

**Comment by tanys123** [comment]
I'm using Laravel storage. I do it by use Cache::flush(). Anyway i can clear cache by key?

**Comment by Kevinrob** [comment]
Sorry I don't know ho Laravel works.

**Comment by Kevinrob** [comment]
@tanys123 Do you find how to do it? I close this issue, feel free to reopen if needed.
