### ISSUE TITLE
Make greedy cache TTL dynamic

### ISSUE THREAD

**Issue by Neirda24** [Kevinrob/guzzle-cache-middleware#98]
When using the greedy cache we must set the TTL in the constructor. It would be a good idea to make it dynamic (maybe using a custom header in the request ?).

**Comment by Kevinrob** [comment]
Yes, that can be a good feature!

**Comment by bpolaszek** [comment]
Hey there,

I know I'm 1 year late on that topic but I did not notice it before. 

I'm really against the fact that the library _modifies_ request objects (even if they're immutable). That's what the [DelegatingCacheStrategy](https://github.com/Kevinrob/guzzle-cache-middleware/blob/master/src/Strategy/Delegate/DelegatingCacheStrategy.php) was designed for (changing strategy based on the request). It's a little more complex to use to achieve the same goal, but I'd have worked on improving this before having no other choice to touch on request objects.

Just saying :smiley_cat:

**Comment by Kevinrob** [comment]
@bpolaszek But we don't modifies request objects, do we?

**Comment by bpolaszek** [comment]
Technically you don't, because PSR-7 objects are immutable, but my point is that you delegate to the Request object the responsibility to carry an information which is out of its scope. Nothing really important here, just quibbling with OOP :smile:

**Comment by bpolaszek** [comment]
Another solution would have been to fake a real `Cache-Control` header, which would have behaved the same.

**Comment by Kevinrob** [comment]
Okay, I understand your point! It's true.
Both methods are possible with this. 😄
